spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/job-offer
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
offer:
  offer-downloader:
    http:
      client:
        config:
          connectionTimeOut: 1000
          readTimeOut: 1000
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 5057
  scheduler:
    request:
      delay: PT3H

scheduling:
  enabled: true

app:
  security:
    expirationMs: 604800000
    issuer: Job offer
    secret: secret